### ISSUE TITLE
[Request] Reupload of the data folder

### ISSUE THREAD

**Issue by FluffyEevee** [droke/fusion#6]
Pretty simple, the wiki link (http://inervate.com/downloads/fusion.zip) seems to be not working and the addon itself doesn't create a data/fusion/mysql.txt

So I wonder if you could re-upload the folder somewhere.

**Comment by droke** [comment]
Seems I haven't paid my website hosting, I've uploaded it to the github now:

https://github.com/droke/fusion/blob/master/fusion_data_sample.zip

**Comment by FluffyEevee** [comment]
Thanks :D
